services:
  baymax:
    build: .
    env_file:
      - path: ./.env
    volumes: 
      - ./models:/baymax/models
    command: bash -c "cd /baymax && python main.py"
    deploy:
      resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]


