services:
  baymax:
    build: .
    env_file:
      - path: ./.env
    command: bash -c "cd /baymax && python main.py"
    ## modify or remove the below config to suit your system
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]