services:
  baymax:
    build: .
    env_file:
      - path: ./.env
    volumes: 
      - ./models:/baymax/models
    command: bash -c "cd /baymax && python main.py"
    # vvv comment this section out if you don't want docker to access GPU resources vvv
    deploy:
      resources:
          reservations:
            devices:
              - driver: nvidia # update to match gpu
                count: 1
                capabilities: [gpu]


